polls/urls.py
from django.urls import path
from . import views


app_name="polls"
urlpatterns=[
    path('',views.index,name='index'),
    path('<int:question_id>/',views.detail,name='detail'),
    path('<int:question_id>/result/',views.result,name='result'),
    path('<int:question_id>/vote/',views.vote,name='vote')
]

untitled3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('control/', admin.site.urls),
    path('polls/',include('polls.urls'))
]

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('data published')
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
from django.template import loader
from django.shortcuts import render,get_object_or_404
from django.http import Http404

# def index(reuqest):
#     return HttpResponse("Hello, world. You're at the polls index.")
# def index(request):
#     latest_question_list=Question.objects.order_by("-pub_date")[:5]
#     output=",".join(q.question_text for q in latest_question_list)
#     return HttpResponse(output)
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context={'latest_question_list': latest_question_list}
    return render(request,'polls/index.html',context)

# def detail(request,question_id):
#     return HttpResponse("You're looking at question %s." % question_id)
def detail(request,question_id):
    # try:
    #     question=Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("question is nor exist")
    question=get_object_or_404(Question,pk=question_id)
    return render(request,"polls/detail.html",{"question":question})

def result(request,question_id):
    response= "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(requese,question_id):
    return HttpResponse("You're voting on question %s." % question_id)




# Create your views here.

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#    <h1>{{question.question_text}}</h1>#}
{#    <ul>#}
{#        {% for choice in question.choice_set.all %}#}
{#            <li>{{ choice.choice_text }}</li>#}
{#        {% endfor %}#}
{#    </ul>#}

    <h1>{{ question.question_text }}</h1>
    {% if error_masage %}<p><strong>{{ error_masage }}</strong></p>{% endif %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
{#            <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>#}
{#            <li><a href="{% url 'detail' question.id %}">{{question.question_text }}</a>></li>#}
            <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text }}</a>></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>
</html>